[build]
  command = "yarn rw db up --no-db-client && yarn rw build"
  publish = "web/dist"
  functions = "api/dist/functions"

[dev]
  command = "yarn rw dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin/tips/*"
  to = "/admin/tips/:splat"
  status = 200
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}